### ISSUE TITLE
PoP miner java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter

### ISSUE THREAD

**Issue by michael-kernel-sanders** [VeriBlock/nodecore-releases#63]
PoP not working in nodecore-pop-0.2.4-rc.1

2018-07-25 06:25:13,107 ERROR [miner] n.m.pop.i [PoPMiningOperation.java:259] java.lang.NoClassDefFoundError: javax
/xml/bind/DatatypeConverter
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at nodecore.miners.pop.i.a(PoPMiningOperation.java:254)
        at nodecore.miners.pop.i.c(PoPMiningOperation.java:92)
        at nodecore.miners.pop.e.a(DefaultPoPMiner.java:134)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at nodecore.miners.pop.a.b.<init>(BitcoinMerkleTree.java:67)
        at nodecore.miners.pop.d.c.a(DefaultBitcoinService.java:330)
        at nodecore.miners.pop.i.n(PoPMiningOperation.java:378)
        at nodecore.miners.pop.i.b(PoPMiningOperation.java:270)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        ... 1 common frames omitted
2018-07-25 06:25:13,108 ERROR [ForkJoinPool.commonPool-worker-1] n.m.p.s.d [DefaultShell.java:124] [d8975c24] A run
ning action was interrupted. Operation can be resubmitted.
2018-07-25 06:25:13,108 INFO [pool-29-thread-1] n.m.p.d.c [DefaultBitcoinService.java:322] Finished downloading blo
ck with hash 00000000000000336736e86da308f8616abfe48feb445beae1597119547b06a0
2018-07-25 06:25:13,109 ERROR [miner] n.m.pop.i [PoPMiningOperation.java:259] java.lang.NoClassDefFoundError: javax
/xml/bind/DatatypeConverter

**Comment by JoshRack** [comment]
No longer relevant.
